<?php

return [

    'FORMAT_CURRENCY_METHOD_ONE'    => 1,
    'FORMAT_CURRENCY_METHOD_TWO'    => 2,
    'FORMAT_CURRENCY_METHOD_THREE'  => 3,
    'FIREBASE_API_KEY'				=>'AAAAUG7Snkg:APA91bFdUnrMQwY_hJ3mD0MLj_vjCpvlXFBQbuRykSIaSwFnyxv7dd-PNKsIUhWnSX8dxj_zmCgPaG06oqTWms0PtEKX01h5ulNeDB71iqX9HiabOWfA64jlYp5Eq8sMMXm9UfOjKFkN',
    'RECORD_PER_PAGE' => 20,
    'THREAD_COUNT' => 3,
    'SUPRISE_FLUSH' => 'flushme'

];
